#!/usr/bin/env bash
# compose.sh: wrapper to run PioDocker with a configurable number of workers.
# Usage: WORKER_COUNT=3 ./compose.sh up --build
# The leader (pio01) always starts; WORKER_COUNT defines how many workers are added.
set -euo pipefail

cd "$(dirname "$0")"

WORKER_COUNT="${WORKER_COUNT:-1}"

if ! [[ "$WORKER_COUNT" =~ ^[0-9]+$ ]]; then
  echo "Error: WORKER_COUNT must be an integer >= 0 (got: '$WORKER_COUNT')" >&2
  exit 1
fi

# Full list: leader + workers
WORKER_NAMES="pio01"
for i in $(seq 1 "$WORKER_COUNT"); do
  WORKER_NAMES="$WORKER_NAMES $(printf 'worker%02d' "$i")"
done

# Ensure per-worker config (worker01 uses the original dir; the rest are generated from the template)
for i in $(seq 1 "$WORKER_COUNT"); do
  name=$(printf 'worker%02d' "$i")
  dir=".pioreactor-worker"
  if [ "$i" -gt 1 ]; then
    dir=".pioreactor-worker-${name}"
    if [ ! -f "$dir/config.ini" ] && [ -f ".pioreactor-worker/config.ini" ]; then
      mkdir -p "$dir"
      sed "s/worker01/${name}/g" .pioreactor-worker/config.ini > "$dir/config.ini"
      echo "Created $dir/config.ini from template"
    fi
  fi
done

# Sync [cluster.addresses] in the leader config
python3 - "$WORKER_COUNT" <<'PYEOF'
import configparser
import sys

path = ".pioreactor/config.ini"
n = int(sys.argv[1])
names = ["pio01"] + ["worker%02d" % i for i in range(1, n + 1)]

cfg = configparser.ConfigParser(interpolation=None)
cfg.optionxform = str
cfg.read(path)
if not cfg.has_section("cluster.addresses"):
    cfg.add_section("cluster.addresses")
cfg["cluster.addresses"] = {k: k for k in names}
from io import StringIO
buf = StringIO()
cfg.write(buf, space_around_delimiters=False)
with open(path, "w") as f:
    f.write(buf.getvalue().rstrip("\n") + "\n")
print(f"[cluster.addresses] synced in {path}: {', '.join(names)}")
PYEOF

# Generate override with the N workers
OVERRIDE=".compose-workers.yml"
: > "$OVERRIDE"
cat >> "$OVERRIDE" <<EOF
# Generated by compose.sh. DO NOT edit.
services:
  backend:
    environment:
      WORKER_NAMES: "$WORKER_NAMES"
EOF

for i in $(seq 1 "$WORKER_COUNT"); do
  name=$(printf 'worker%02d' "$i")
  ssh_port=$((2222 + i))
  if [ "$i" -eq 1 ]; then
    dot_pioreactor="./.pioreactor-worker"
  else
    dot_pioreactor="./.pioreactor-worker-${name}"
  fi
  cat >> "$OVERRIDE" <<EOF
  ${name}:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        PIO_VERSION: ${PIO_VERSION:-26.6.0}
    hostname: ${name}
    container_name: ${name}
    ports:
      - "${ssh_port}:22"
    volumes:
      - ${dot_pioreactor}:/home/pioreactor/.pioreactor
      - ${name}_cache:/tmp/pioreactor_cache
    environment:
      HOSTNAME: ${name}
      TESTING: "1"
      GLOBAL_CONFIG: /home/pioreactor/.pioreactor/config.ini
      DOT_PIOREACTOR: /home/pioreactor/.pioreactor
      RUN_PIOREACTOR: /tmp/pioreactor_cache
      PLUGINS_DEV: /home/pioreactor/plugins_dev
      MODEL_NAME: pioreactor_20ml
      MODEL_VERSION: "1.1"
      HARDWARE: "1.2"
    depends_on:
      mosquitto:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - lab-network
EOF
done

if [ "$WORKER_COUNT" -gt 0 ]; then
  printf 'volumes:\n' >> "$OVERRIDE"
  for i in $(seq 1 "$WORKER_COUNT"); do
    printf '  %s_cache:\n' "$(printf 'worker%02d' "$i")" >> "$OVERRIDE"
  done
fi

echo "Generated $OVERRIDE with $WORKER_COUNT worker(s) and WORKER_NAMES='$WORKER_NAMES'"

exec docker compose -f docker-compose.yml -f "$OVERRIDE" "$@"