services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped
    networks:
    - lab-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    hostname: pio01
    ports:
      - "2222:22"
      - "4999:4999"
    volumes:
      - ./.pioreactor:/home/pioreactor/.pioreactor
      - pioreactor_cache:/tmp/pioreactor_cache
    environment:
      HOSTNAME: pio01
      TESTING: "1"
      GLOBAL_CONFIG: /home/pioreactor/.pioreactor/config.ini
      DOT_PIOREACTOR: /home/pioreactor/.pioreactor
      RUN_PIOREACTOR: /tmp/pioreactor_cache
      PLUGINS_DEV: /home/pioreactor/plugins_dev
      MODEL_NAME: pioreactor_20ml
      MODEL_VERSION: "1.1"
      HARDWARE: "1.2"
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
    - lab-network

  worker01:
    build:
      context: .
      dockerfile: Dockerfile.worker
    hostname: worker01
    ports:
      - "2223:22"
    volumes:
      - ./.pioreactor-worker:/home/pioreactor/.pioreactor
      - worker01_cache:/tmp/pioreactor_cache
    environment:
      HOSTNAME: worker01
      TESTING: "1"
      GLOBAL_CONFIG: /home/pioreactor/.pioreactor/config.ini
      DOT_PIOREACTOR: /home/pioreactor/.pioreactor
      RUN_PIOREACTOR: /tmp/pioreactor_cache
      PLUGINS_DEV: /home/pioreactor/plugins_dev
      MODEL_NAME: pioreactor_20ml
      MODEL_VERSION: "1.1"
      HARDWARE: "1.2"
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
    - lab-network

  emulator:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./.pioreactor:/home/pioreactor/.pioreactor
      - ./emulator/state:/app/state
      - ./emulator/configs:/app/configs
    environment:
      STATE_DIR: /app/state
      CONFIG_PATH: /app/configs/EMULATOR_config.json
      MQTT_BROKER: mosquitto
      MQTT_PORT: "1883"
      DATA_DIR: /app/state
      PIO_DB_PATH: /home/pioreactor/.pioreactor/storage/pioreactor.sqlite
    depends_on:
      - mosquitto
      - backend
    restart: unless-stopped
    networks:
    - lab-network

volumes:
  mosquitto_data:
  pioreactor_cache:
  worker01_cache:
networks:
  lab-network:
    external: true