[global]
   workgroup = WORKGROUP
   map to guest = Bad User
   security = user
   guest account = nobody

[LabCompartido]
   path = /app/model
   guest ok = yes
   browseable = yes
   read only = yes
